<a href="https://colab.research.google.com/github/plaban1981/Pytorch_DL/blob/main/Pytorch_Pocket_Referrence_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
# Created from preexisting arrays
w = torch.tensor([1,2,3]) #list
print(w)
w = torch.tensor((1,2,3)) # Tuple
print(w)
w = torch.tensor(np.array([1,2,3])) #numpy array
print(w)
# Initialized by size
w = torch.empty(100,200)
print(w)
w = torch.zeros(100,200)
print(w)
w = torch.ones(100,200)
print(w)

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])


In [3]:
# Initialized by size with random values
w = torch.rand(100,200)
print(w)
w = torch.randn(100,200)
print(w)
w = torch.randint(5,10,(100,200))
print(w)
# Initialized with specified data type or device
w = torch.empty((100,200), dtype=torch.float64,device="cpu")
print(w)
# Initialized to have the same size, data type,
# and device as another tensor
x = torch.empty_like(w)
print(x)

tensor([[0.2225, 0.6783, 0.4923,  ..., 0.0805, 0.1880, 0.0098],
        [0.0916, 0.4093, 0.8508,  ..., 0.6457, 0.8968, 0.5150],
        [0.0268, 0.4077, 0.1794,  ..., 0.3196, 0.3250, 0.1898],
        ...,
        [0.3910, 0.1441, 0.1026,  ..., 0.2273, 0.6439, 0.9102],
        [0.5851, 0.8153, 0.6320,  ..., 0.2890, 0.6013, 0.0564],
        [0.3327, 0.5044, 0.2245,  ..., 0.4684, 0.8679, 0.2474]])
tensor([[ 1.2882e+00, -9.1558e-01,  7.8231e-01,  ..., -1.0210e-01,
         -8.5493e-01, -1.4500e+00],
        [-1.1089e-03,  5.9136e-01, -2.5820e-01,  ...,  9.9834e-01,
          8.0106e-02, -4.9474e-01],
        [ 1.0670e+00,  1.5238e+00,  3.2759e-01,  ...,  1.1444e+00,
          1.2477e+00, -5.1907e-01],
        ...,
        [-6.2720e-01, -3.5206e-01, -6.2252e-01,  ..., -4.1726e-02,
          9.7799e-01,  5.0047e-01],
        [-3.9310e-01,  2.4846e-02, -8.2506e-01,  ...,  1.3258e+00,
         -3.5108e-01, -7.9355e-01],
        [ 1.4121e+00,  1.9977e-01,  6.1446e-01,  ..., -7.2942e-01,
       

In [4]:
x.dtype

torch.float64

In [5]:
x.device

device(type='cpu')

In [6]:
x.shape

torch.Size([100, 200])

In [7]:
x.ndim

2

In [8]:
x.requires_grad

False

In [9]:
x.grad #Contains the actual gradients if requires_grad is True

In [10]:
torch.eye(3,4) #Creates a 2D tensor with ones on thediagonal and zeros everywhere else

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [11]:
torch.full((2,3),1.5) # Creates a tensor filled with fill_value=1.5

tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]])

In [12]:
x.grad_fn #Stores the graph computation function used if requires_grad is True

## Data Types

In [13]:
# Specify the data type at creation using dtype
w = torch.tensor([1,2,3], dtype=torch.float32)
w

tensor([1., 2., 3.])

In [14]:
# Use the casting method to cast to a new data type
w.int() # w remains a float32 after the cast
w = w.int() # w changes to an int32 after the cast
w

tensor([1, 2, 3], dtype=torch.int32)

In [15]:
# Use the to() method to cast to a new type
w = w.to(torch.float64)
w = w.to(dtype=torch.float64)
w

tensor([1., 2., 3.], dtype=torch.float64)

In [16]:
# Python automatically converts data types during
# operations
x = torch.tensor([1,2,3], dtype=torch.int32)
y = torch.tensor([1,2,3], dtype=torch.float32)
print(x)
print(y)
z = x + y

print(z.dtype)

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])
torch.float32


## Indexing, Slicing, Combining, and Splitting Tensors

In [17]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [18]:
# Indexing, returns a tensor
print(x[1,1])

tensor(4)


In [19]:
# Indexing, returns a value as a Python number
print(x[1,1].item())

4


In [20]:
# Slicing
print(x[:2,1])

tensor([2, 4])


In [21]:
# Boolean indexing
# Only keep elements less than 5
print(x[x<5])

tensor([1, 2, 3, 4])


In [22]:
# Transpose array; x.t() or x.T can be used
print(x.t())

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])


In [23]:
# Change shape; usually view() is preferred over
# reshape()
print(x.view((2,4)))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [24]:
# Combining tensors
y = torch.stack((x, x))
print(y)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])


In [32]:
x

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [33]:
x.squeeze()

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [25]:
# Splitting tensors
a,b = x.unbind(dim=1)
print(a,b)

tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])


In [26]:
c,d = y.unbind(dim=0)

In [27]:
print(c,d)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [30]:
c,d = y.unbind()

In [29]:
c

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [31]:
d

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [36]:
y.shape

torch.Size([2, 4, 2])

In [35]:
y.squeeze().shape

torch.Size([2, 4, 2])

In [40]:
#torch.item()=> returns return Python number from a tensor containing a single value.
x = torch.tensor([1], dtype=torch.int32)
x.item()

1

* Use view() instead of reshape() for reshaping tensors in
most cases. 
* Using reshape() may cause the tensor to be
copied, depending on its layout in memory. 
* view()
ensures that will not cause the tensor to be copied.
* The **torch.squeeze()** function is used often in deep learning
to remove an unused dimension. For example, a batch
of images with a single image can be reduced from 4D to
3D using squeeze().
* The **torch.unsqueeze()** function is often used in deep
learning to add a dimension of size 1. Since most PyTorch
models expect a batch of data as an input, you could apply
unsqueeze() when you only have one data sample. For
example, you can pass a 3D image into torch.unsqueeze()
to create a batch of one image.

## Automatic Differentiation (Autograd)

In [46]:
x = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float, requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [47]:
print(x.grad)

None


In [48]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [49]:
f = x.pow(2).sum()
print(f)

tensor(91., grad_fn=<SumBackward0>)


In [50]:
f.backward()
print(x.grad)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


* The f.backward() function performs the differentiation with
respect to f and stores df / dx in the x.grad attribute
* df / dx = 2x